// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Cumprimentar.proto
// Protobuf Java Version: 4.31.1

package cumprimentar;

@com.google.protobuf.Generated
public final class CumprimentarProto {
  private CumprimentarProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      CumprimentarProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CumprimentarRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CumprimentarRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();
  }
  /**
   * Protobuf type {@code CumprimentarRequest}
   */
  public static final class CumprimentarRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CumprimentarRequest)
      CumprimentarRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        CumprimentarRequest.class.getName());
    }
    // Use CumprimentarRequest.newBuilder() to construct.
    private CumprimentarRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CumprimentarRequest() {
      nome_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cumprimentar.CumprimentarProto.internal_static_CumprimentarRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cumprimentar.CumprimentarProto.internal_static_CumprimentarRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cumprimentar.CumprimentarProto.CumprimentarRequest.class, cumprimentar.CumprimentarProto.CumprimentarRequest.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nome_ = "";
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    @java.lang.Override
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nome_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nome_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nome_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cumprimentar.CumprimentarProto.CumprimentarRequest)) {
        return super.equals(obj);
      }
      cumprimentar.CumprimentarProto.CumprimentarRequest other = (cumprimentar.CumprimentarProto.CumprimentarRequest) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cumprimentar.CumprimentarProto.CumprimentarRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CumprimentarRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CumprimentarRequest)
        cumprimentar.CumprimentarProto.CumprimentarRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cumprimentar.CumprimentarProto.internal_static_CumprimentarRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cumprimentar.CumprimentarProto.internal_static_CumprimentarRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cumprimentar.CumprimentarProto.CumprimentarRequest.class, cumprimentar.CumprimentarProto.CumprimentarRequest.Builder.class);
      }

      // Construct using cumprimentar.CumprimentarProto.CumprimentarRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nome_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cumprimentar.CumprimentarProto.internal_static_CumprimentarRequest_descriptor;
      }

      @java.lang.Override
      public cumprimentar.CumprimentarProto.CumprimentarRequest getDefaultInstanceForType() {
        return cumprimentar.CumprimentarProto.CumprimentarRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cumprimentar.CumprimentarProto.CumprimentarRequest build() {
        cumprimentar.CumprimentarProto.CumprimentarRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cumprimentar.CumprimentarProto.CumprimentarRequest buildPartial() {
        cumprimentar.CumprimentarProto.CumprimentarRequest result = new cumprimentar.CumprimentarProto.CumprimentarRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cumprimentar.CumprimentarProto.CumprimentarRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nome_ = nome_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cumprimentar.CumprimentarProto.CumprimentarRequest) {
          return mergeFrom((cumprimentar.CumprimentarProto.CumprimentarRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cumprimentar.CumprimentarProto.CumprimentarRequest other) {
        if (other == cumprimentar.CumprimentarProto.CumprimentarRequest.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nome_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nome_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        nome_ = getDefaultInstance().getNome();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nome_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CumprimentarRequest)
    }

    // @@protoc_insertion_point(class_scope:CumprimentarRequest)
    private static final cumprimentar.CumprimentarProto.CumprimentarRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cumprimentar.CumprimentarProto.CumprimentarRequest();
    }

    public static cumprimentar.CumprimentarProto.CumprimentarRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CumprimentarRequest>
        PARSER = new com.google.protobuf.AbstractParser<CumprimentarRequest>() {
      @java.lang.Override
      public CumprimentarRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CumprimentarRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CumprimentarRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cumprimentar.CumprimentarProto.CumprimentarRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CumprimentarReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CumprimentarReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mensagem = 1;</code>
     * @return The mensagem.
     */
    java.lang.String getMensagem();
    /**
     * <code>string mensagem = 1;</code>
     * @return The bytes for mensagem.
     */
    com.google.protobuf.ByteString
        getMensagemBytes();
  }
  /**
   * Protobuf type {@code CumprimentarReply}
   */
  public static final class CumprimentarReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CumprimentarReply)
      CumprimentarReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        CumprimentarReply.class.getName());
    }
    // Use CumprimentarReply.newBuilder() to construct.
    private CumprimentarReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CumprimentarReply() {
      mensagem_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cumprimentar.CumprimentarProto.internal_static_CumprimentarReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cumprimentar.CumprimentarProto.internal_static_CumprimentarReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cumprimentar.CumprimentarProto.CumprimentarReply.class, cumprimentar.CumprimentarProto.CumprimentarReply.Builder.class);
    }

    public static final int MENSAGEM_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mensagem_ = "";
    /**
     * <code>string mensagem = 1;</code>
     * @return The mensagem.
     */
    @java.lang.Override
    public java.lang.String getMensagem() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensagem_ = s;
        return s;
      }
    }
    /**
     * <code>string mensagem = 1;</code>
     * @return The bytes for mensagem.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMensagemBytes() {
      java.lang.Object ref = mensagem_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensagem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mensagem_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, mensagem_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(mensagem_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, mensagem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cumprimentar.CumprimentarProto.CumprimentarReply)) {
        return super.equals(obj);
      }
      cumprimentar.CumprimentarProto.CumprimentarReply other = (cumprimentar.CumprimentarProto.CumprimentarReply) obj;

      if (!getMensagem()
          .equals(other.getMensagem())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MENSAGEM_FIELD_NUMBER;
      hash = (53 * hash) + getMensagem().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cumprimentar.CumprimentarProto.CumprimentarReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cumprimentar.CumprimentarProto.CumprimentarReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cumprimentar.CumprimentarProto.CumprimentarReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cumprimentar.CumprimentarProto.CumprimentarReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CumprimentarReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CumprimentarReply)
        cumprimentar.CumprimentarProto.CumprimentarReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cumprimentar.CumprimentarProto.internal_static_CumprimentarReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cumprimentar.CumprimentarProto.internal_static_CumprimentarReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cumprimentar.CumprimentarProto.CumprimentarReply.class, cumprimentar.CumprimentarProto.CumprimentarReply.Builder.class);
      }

      // Construct using cumprimentar.CumprimentarProto.CumprimentarReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mensagem_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cumprimentar.CumprimentarProto.internal_static_CumprimentarReply_descriptor;
      }

      @java.lang.Override
      public cumprimentar.CumprimentarProto.CumprimentarReply getDefaultInstanceForType() {
        return cumprimentar.CumprimentarProto.CumprimentarReply.getDefaultInstance();
      }

      @java.lang.Override
      public cumprimentar.CumprimentarProto.CumprimentarReply build() {
        cumprimentar.CumprimentarProto.CumprimentarReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cumprimentar.CumprimentarProto.CumprimentarReply buildPartial() {
        cumprimentar.CumprimentarProto.CumprimentarReply result = new cumprimentar.CumprimentarProto.CumprimentarReply(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cumprimentar.CumprimentarProto.CumprimentarReply result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mensagem_ = mensagem_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cumprimentar.CumprimentarProto.CumprimentarReply) {
          return mergeFrom((cumprimentar.CumprimentarProto.CumprimentarReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cumprimentar.CumprimentarProto.CumprimentarReply other) {
        if (other == cumprimentar.CumprimentarProto.CumprimentarReply.getDefaultInstance()) return this;
        if (!other.getMensagem().isEmpty()) {
          mensagem_ = other.mensagem_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mensagem_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object mensagem_ = "";
      /**
       * <code>string mensagem = 1;</code>
       * @return The mensagem.
       */
      public java.lang.String getMensagem() {
        java.lang.Object ref = mensagem_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mensagem_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mensagem = 1;</code>
       * @return The bytes for mensagem.
       */
      public com.google.protobuf.ByteString
          getMensagemBytes() {
        java.lang.Object ref = mensagem_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mensagem_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mensagem = 1;</code>
       * @param value The mensagem to set.
       * @return This builder for chaining.
       */
      public Builder setMensagem(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mensagem_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string mensagem = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMensagem() {
        mensagem_ = getDefaultInstance().getMensagem();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string mensagem = 1;</code>
       * @param value The bytes for mensagem to set.
       * @return This builder for chaining.
       */
      public Builder setMensagemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mensagem_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CumprimentarReply)
    }

    // @@protoc_insertion_point(class_scope:CumprimentarReply)
    private static final cumprimentar.CumprimentarProto.CumprimentarReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cumprimentar.CumprimentarProto.CumprimentarReply();
    }

    public static cumprimentar.CumprimentarProto.CumprimentarReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CumprimentarReply>
        PARSER = new com.google.protobuf.AbstractParser<CumprimentarReply>() {
      @java.lang.Override
      public CumprimentarReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CumprimentarReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CumprimentarReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cumprimentar.CumprimentarProto.CumprimentarReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CumprimentarRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CumprimentarRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CumprimentarReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CumprimentarReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022Cumprimentar.proto\"#\n\023CumprimentarRequ" +
      "est\022\014\n\004nome\030\001 \001(\t\"%\n\021CumprimentarReply\022\020" +
      "\n\010mensagem\030\001 \001(\t2K\n\023CumprimentarService\022" +
      "4\n\010dizerOla\022\024.CumprimentarRequest\032\022.Cump" +
      "rimentarReplyB!\n\014cumprimentarB\021Cumprimen" +
      "tarProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CumprimentarRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CumprimentarRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CumprimentarRequest_descriptor,
        new java.lang.String[] { "Nome", });
    internal_static_CumprimentarReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CumprimentarReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CumprimentarReply_descriptor,
        new java.lang.String[] { "Mensagem", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
